name: CI

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v9
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: Check formatting with Prettier
      run: yarn format:check
    - name: Check quality with ESLint
      run: yarn lint
    - name: Check types compile
      run: yarn type-check
    - name: Check tests pass
      run: yarn test
    - name: Check app builds
      run: yarn build